language: C

os:
  - linux
  - osx

sudo: required

install:
- |
  # Install lcov
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install -y lcov
  else if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install lcov
      fi
  fi
  # Install coveralls uploader
  gem install coveralls-lcov


# Build main and tests
script:
- |
  mkdir -p build
  cd build
  cmake -DUNITTESTS=ON -DCOVERAGE=ON ..
  make
  out/qdldl_tester

  # Pefrorm code coverage (only in Linux case for one version of python)
after_success:
- |
  cd ${TRAVIS_BUILD_DIR}
  if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      cd ${TRAVIS_BUILD_DIR}/build
      lcov --directory . --capture -o coverage.info # capture coverage info
      lcov --remove coverage.info "${TRAVIS_BUILD_DIR}/tests/*" \
          "${TRAVIS_BUILD_DIR}/examples/*" \
          -o coverage.info # filter out tests and unnecessary files
      lcov --list coverage.info # debug before upload
      coveralls-lcov coverage.info # uploads to coveralls
  fi

