# Not a .NET project. We build it in the install script
build: false

platform:
  - x64
  - x86

environment:
  CMAKE_PROJECT: Visual Studio 15 2017

init:
  # Uncomment for remote desktop debug
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# install:
#   - "%APPVEYOR_BUILD_FOLDER%\\ci\\appveyor\\install.cmd"
#


# Setup Cmake project
before_build:
- cmd: >-
    IF "%PLATFORM%"=="x64" (
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    ) ELSE (
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
    )


# Perform tests
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -G"%CMAKE_PROJECT%" -DUNITTESTS=ON ..
  - cmake --build .
  - %APPVEYOR_BUILD_FOLDER%\build\out\qdldl_tester.exe
  - if errorlevel 1 exit /b 1


# on_finish:
#   # Uncomment for remote desktop debug
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
